name: Go Syntax Check

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x  # Set your desired Go version

    - name: Install linter
      run: go get -u golang.org/x/lint/golint

    - name: Run Go Linter
      run: |
        go vet ./...
        golint -set_exit_status ./...

    - name: Reject if Go Linter Errors
      run: |
        if [ $? -eq 1 ]; then
          echo "Go Linter Errors Found"
          exit 1
        fi